name: artifact_generation
on: [push, workflow_dispatch]
jobs:
  set_outputs:
    runs-on: ubuntu-latest
    outputs: 
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Publish_website
        id: publish
        run: find src/assests/*.js -type f -exec dir rcho 'script-file={}' >> $GITHUB_OUTPUT ';'
  artifact_upload:
    needs: set_outputs
    runs-on: ubuntu-latest
    steps:
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
         name: web-artifacts
         path: |
          .github/workflows
          package.json
          package-lock.*
  download_artifacts:
    needs: artifact_upload
    runs-on: ubuntu-latest
    steps:
      - name: artifacts_download
        uses: actions/download-artifact@v3
        with:
         name: web-artifacts
      - name: show_artifacts
        run: ls
      - name: output filename
        run: echo "{{needs.set_outputs.outputs.script-file}}"
      - name: deploying
        run: echo "SUCCESSFULLY DEPLOYED"
