name: printdate
on: [workflow_dispatch ]
jobs:
  printing_date:
    runs-on : ubuntu-latest
    steps: 
        - name: get a date
          run: echo "NOW:$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
        - name: print_dtate
          run: echo $NOW
