name: printdate
on: [push, workflow_dispatch ]
env:
  CURRENT_DATE: $(date +%Y-%m-%d)
jobs:
  printing_date:
    runs-on : ubuntu-latest
    steps:
        - name: print_date
          run: echo $CURRENT_DATE
