name: printdate
on: [push, workflow_dispatch ]
jobs:
  printing_date:
    runs-on : ubuntu-latest
    steps: 
        - name: get a date
          run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        - name: print_date
          run: echo $NOW
