name: printdate
on: [workflow_dispatch ]
env:
  NOW: $(date + '%Y-%m-%d') >> $GITHUB_OUTPUT
jobs:
  printing_date:
    runs-on : ubuntu-latest
    steps: 
        - name: printdtate
          run: echo $NOW
