name: printdate
on: [push, workflow_dispatch ]
jobs:
  printing_date:
    runs-on : ubuntu-latest
    steps:
        - name: get current date
          run: echo "CURRENT_DATE=$(date +%Y_%m_%d)" >> $GITHUB_ENV
        - name: print_date
          run: echo $CURRENT_DATE
