name: workflow2
on: [push , workflow_dispatch]
jobs:
  Code_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
  Run_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
  Test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: npm run test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: npm run build
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Deploying..."
