name: Test

on:
  workflow_dispatch:
    inputs:
      puppy:
        description: 'creation'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
